language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
install:
- python setup.py bdist_wheel
- pip install flake8
- pip install dist/iso_3166_1-*.whl
- pip install -e .[tests]
script:
- flake8 .
- py.test -vv
